### ISSUE TITLE
Image Processing libraries in Blender

### ISSUE THREAD

**Issue by vikasTmz** [ApoorvaJ/BlenderSFM#3]
Hi Apporva,

Which image processing library did you use here? Or did you just use binary files to get `sift features` etc.? 
I've read importing libraries like opencv can be an issue because of the different python versions used.

**Comment by ApoorvaJ** [comment]
Hey,

It's been quite a while since I worked on this, so my memory is a bit rusty. From what I remember, I had used native binaries, which I was calling from Python. If I had to do this today, I'd probably go with a similar approach, but write/adapt custom GPU-accelerated native code to do SIFT and bundle adjustment. That way you can have your own SFM pipeline, and only loosely couple with Blender and its version of Python.
